joint_controller_params:
    # KP = [0.1, 0.2, 0.2, 0.4, 0.3, 0.15, 0, 0]*2     # P Gain 7,8번은 스위치로 변경되었으므로 게인값 없음
    # KD = [0.2, 0.3, 0.3, 0.45, 0.1, 0.1, 0, 0]*2    # D Gain 7,8번은 스위치로 변경되었으므로 게인값 없음
  R1:
    p: 0.1
    i: 0.01
    d: 0.2
  R2:
    p: 0.2
    i: 0.01
    d: 0.3
  R3:
    p: 0.2
    i: 0.01
    d: 0.3
  R4:
    p: 0.4
    i: 0.01
    d: 0.45
  R5:
    p: 0.3
    i: 0.01
    d: 0.1
  R6:
    p: 0.15
    i: 0.01
    d: 0.1
  R7:
    p: 0
    i: 0.01
    d: 0
  R8:
    p: 0
    i: 0.01
    d: 0

  L1:
    p: 0.1
    i: 0.01
    d: 0.2
  L2:
    p: 0.2
    i: 0.01
    d: 0.3
  L3:
    p: 0.2
    i: 0.01
    d: 0.3
  L4:
    p: 0.4
    i: 0.01
    d: 0.45
  L5:
    p: 0.3
    i: 0.01
    d: 0.1
  L6:
    p: 0.15
    i: 0.01
    d: 0.1
  L7:
    p: 0
    i: 0.01
    d: 0
  L8:
    p: 0
    i: 0.01
    d: 0